version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      storybook:
        patterns:
          - storybook
          - '@storybook/*'
      vitest:
        patterns:
          - vitest
          - '@vitest/*'
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - 'actions/*'
          - 'pnpm/action-setup'
